<?php

/**
 * @file
 * Provides the ability to override views entities in Page manager.
 */


/**
 * Implements hook_ctools_plugin_directory().
 */
function eck_pm_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'page_manager' && $plugin_type == 'tasks') {
    return 'plugins/' . $plugin_type;
  }
}


/**
 * Gets the possible views of entities.
 *
 * @param mixed $task_id
 *   The task ID.
 *
 * @return array
 *   An array with pages and their settings.
 */
function eck_pm_get_eck_pages($task_id = NULL) {
  $entity_types = EntityType::loadAll();

  $pages = array();
  module_load_include('inc', 'eck', 'eck.entity');
  foreach ($entity_types as $info) {
    $entity_type = $info->name;
    $data = new stdClass();
    $data->name = $entity_type . '_view';
    $data->label = t('!entity_type Template', array('!entity_type' => $info->label));
    $data->context = 'entity|' . $entity_type . '|id';
    $data->entity_type = $entity_type;
    $data->paths = array();
    foreach (Bundle::loadByEntityType($info) as $bundle) {
      $crud_info = get_bundle_crud_info($info->name, $bundle->name);
      $data->paths[] = $crud_info['view']['path'];
    }
    $data->type = 'Normal';

    $pages[$entity_type . '_view'] = $data;
  }

  if ($task_id) {
    return $pages[$task_id];
  }

  return $pages;
}

