<?php

/**
 * @file
 * Events voipscript and sms handling.
 */

/**
 * Implements hook_voipscript_load_script().
 */
function incourage_events_voipscript_load_script($script_name, $params = NULL) {
  if ($script_name == 'incourage_event') {
    module_load_include('inc', 'incourage_events', 'incourage_events.script');
    $caller = empty($params['caller']) ? '' : $params['caller'];
    $node = node_load($params['entity_id']);
    return _incourage_events_event_script($node, $caller);
  }
  elseif ($script_name == 'incourage_location') {
    module_load_include('inc', 'incourage_events', 'incourage_events.script');
    $caller = empty($params['caller']) ? '' : $params['caller'];
    $node = node_load($params['entity_id']);
    return _incourage_events_location_script($node, $caller);
  }
  elseif ($script_name == 'incourage_upcoming') {
    module_load_include('inc', 'incourage_events', 'incourage_events.script');
    return _incourage_events_upcoming_script();
  }
  elseif ($script_name == 'incourage_event_read_view') {
    module_load_include('inc', 'incourage_events', 'incourage_events.script');
    $view_name = $params['view_name'];
    $display_id = $params['display_id'];
    $filters = isset($params['filters']) ? json_decode($params['filters'], true) : array();
    $args = isset($params['args']) ? json_decode($params['args'], true) : array();
    return incourage_event_read_view($view_name, $display_id, $filters, $args);
  }
  elseif ($script_name == 'incourage_events_sms') {
    module_load_include('inc', 'incourage_events', 'incourage_events.script');
    return _incourage_events_sms_script();
  }
}

/**
 * Load a view, pass to script to read.
 *
 * @return VoipScript
 */
function incourage_event_read_view($view_name, $display_id, $filters = array(), $args = array()) {
  $view = views_get_view($view_name);
  if (!$view || !$view->access($display_id)) {
    $script = new VoipScript('incourage_event_error');
    watchdog('incourage_event', 'Unable to load or access view @view_name display @display_id', array('@view_name' => $view_name, '@display_id' => $display_id), WATCHDOG_ERROR);
    $script->addSay('There has been an error accessing the information you require. Sorry.');
    $script->addReturn();
    return $script;
  }
  if (! $view->set_display($display_id)) {
    $script = new VoipScript('incourage_event_error');
    watchdog('incourage_event', 'Unable to set display @display_id on view @view_name', array('@view_name' => $view_name, '@display_id' => $display_id), WATCHDOG_ERROR);
    $script->addSay('There has been an error accessing the information you require. Sorry.');
    $script->addReturn();
    return $script;
  }

  if (! empty($filters)) {
    $view->set_exposed_input($filters);
  }

  $view->pre_execute($args);
  $view->display_handler->preview();
  $view->post_execute();

  $script = _incourage_events_read_view_script($view->result);
  return $script;
}

/**
 * Implements hook_voipscript_get_script_names().
 */
function incourage_events_voipscript_get_script_names() {
  return array(
    'incourage_upcoming',
    'incourage_event',
    'incourage_location',
    'incourage_event_read_view',
    'incourage_events_sms',
  );
}

/**
 * Helper function return event extension sms msg.
 */
function incourage_events_sms_reply($extension) {
  list($entity_type, $entity) = voipextension_get_entity('field_extension', $extension);
  if (!empty($entity)) {
    $msg = '';
    $msg = incourage_events_format_sms($entity);
  }
  else {
    $msg = 'Unknown event extension.';
  }

  return $msg;
}

/**
 * Format SMS text for an event.
 *
 * @todo get the phone number from the variables?
 */
function incourage_events_format_sms($node) {
  if (!empty($node->field_sms_text['und'][0]['value'])) {
    $msg = $node->field_sms_text['und'][0]['value'];
  }
  else {
    list($location, $phone) = _incourage_events_location($node);
    $msg .= $node->field_cost['und'][0]['value'];
    $msg = "[node:title]. [node:field_cost]. [node:field_date]. $location 715.952.9020 ext. " . $node->field_extension['und'][0]['value'];
    $msg = token_replace($msg, array('global' => NULL, 'node' => $node));
    $msg = strip_tags($msg);
  }

  return $msg;
}

/**
 * Format SMS text for an location.
 */
function incourage_events_location_format_sms($node) {
  $msg = strip_tags($node->title) . ': ';
  if ($node->title != $node->field_official_name[0]['value']) {
    $msg .= strip_tags($node->field_official_name[0]['value']) . ', ';
  }
  if (! empty($node->field_address_street[0]['value'])) {
    $msg .= strip_tags($node->field_address_street[0]['value']) . ',';
  }
  if (! empty($node->field_address_city[0]['value'])) {
    $msg .= strip_tags($node->field_address_city[0]['value']) . ', ';
  }

  return $msg;
}

/**
 * Helper function to return correct location information.
 */
function _incourage_events_location($node) {
  if (!empty($node->field_location_reference['und'][0]['nid'])) {
    $location_node = node_load($node->field_location_reference['und'][0]['nid']);
    $location = $location_node->title . ', ' . $location_node->field_address_street['und'][0]['value'] . ', ' . $location_node->field_address_city['und'][0]['value'] . '. ';
    $phone = $location_node->field_phone_text['und'][0]['value'];
  }
  else {
    $location = $node->field_location['und'][0]['value'];
    $phone = '';
  }

  return array($location, $phone);
}

/**
 * Nasty short cut for notifications text. We create
 * a custom token to inclued all the logic we require
 * for selecting what is in the SMS. token_logic would
 * be the alternative if it was still about. Downside
 * here is it is difficult for a site admin to change the
 * text; but as it's custom anyway.
 */

/**
 * Implements hook_token_list().
 */
function incourage_events_token_list($type = 'all') {
  $tokens = array();

  if ($type == 'node' || $type == 'all') {
    $tokens['node']['incourage-events-sms'] = t("Custom event SMS content.");
  }

  return $tokens;
}

/**
 * Implements hook_token_values().
 */
function incourage_events_token_values($type, $object = NULL, $options = array()) {
  $values = array();

  if ($type == 'node' && !empty($object) && $object->type == 'event') {
    $values['incourage-events-sms'] = incourage_events_format_sms($object);
  }

  return $values;
}
