<?php

/**
 * @file
 *   Custom module to send taxonomy term notifications.
 */

function comminfo_notify_cron() {
  $sms = array();
  $tids = array(1, 2, 3, 4, 5); // get tid in vid 1
  foreach ($tids as $tid) {
    // tomorrows events
    $view = views_get_view('upcoming_bulletin');
    $view->set_display('attachment_1');
    $view->set_arguments(array($tid));
    $view->execute();
    $events = $view->result;
    if (! count($events)) {
      continue;
    }

    $messages = array();
    foreach ($events as $event) {
      $node = node_load($event->nid);
      if (count($node->field_sms_text)) {
        $messages[$node->nid] = 'Event tomorrow: ' . $node->field_sms_text['und'][0]['value'];
      }
      else {
        $messages[$node->nid] = 'Event tomorrow: ' . $node->title . ' Extension: ' . $node->field_extension['und'][0]['value'];
      }
    }

    // users to notify
    $user_flags = flag_get_entity_flags('taxonomy_term', $tid, 'sms_topic_updates');

    foreach ($user_flags as $uid => $flag) {
      $user = user_load($uid);
      if (isset($user->field_sms_number['und'][0]['vnid'])) {
        // Phone number not loaded yet.
        $number = db_query('SELECT phone_number FROM voipnumber WHERE vnid = :vnid', array('vnid' => $user->field_sms_number['und'][0]['vnid']))->fetchField();
        if (is_array($sms[$number])) {
          $sms[$number] = array_merge($sms[$number], $messages);
        }
        else {
          $sms[$number] = $messages;
        }
      }
    }
  }

  // Send text. Opting for immediate for now, could be queued.
  foreach ($sms as $number => $message) {
    $call = new VoipCall(array());
    $call->setDestNumber($number);
    $voip_server = voip_default_server();
    $response = $voip_server->send_text($message, $call);
  }
}
