<?php

/**
 * @file
 * Custom module to send taxonomy term notifications.
 */

/**
 * Implements hook_cron().
 *
 * Send SMS messages to all users with flags on SMS topics if there is an event
 * tomorrow.
 */
function comminfo_notify_cron() {
  $sms = array();
  // Get tid in vid 1.
  $tids = array(1, 2, 3, 4, 5);
  foreach ($tids as $tid) {
    // Tomorrows events.
    $view = views_get_view('upcoming_bulletin');
    $view->set_display('attachment_1');
    $view->set_arguments(array($tid));
    $view->execute();
    $events = $view->result;
    if (!count($events)) {
      continue;
    }

    $messages = array();
    foreach ($events as $event) {
      $node = node_load($event->nid);
      if (count($node->field_sms_text)) {
        $messages[$node->nid] = 'Event tomorrow: ' . $node->field_sms_text['und'][0]['value'];
      }
      else {
        $messages[$node->nid] = 'Event tomorrow: ' . $node->title . ' Extension: ' . $node->field_extension['und'][0]['value'];
      }
    }

    // Users to notify.
    $user_flags = flag_get_entity_flags('taxonomy_term', $tid, 'sms_topic_updates');

    foreach ($user_flags as $uid => $flag) {
      $user = user_load($uid);
      if (isset($user->field_sms_number['und'][0]['vnid'])) {
        // Phone number not loaded yet.
        $number = db_query('SELECT phone_number FROM voipnumber WHERE vnid = :vnid', array('vnid' => $user->field_sms_number['und'][0]['vnid']))->fetchField();
        if (is_array($sms[$number])) {
          $sms[$number] = array_merge($sms[$number], $messages);
        }
        else {
          $sms[$number] = $messages;
        }
      }
    }
  }

  // Send text. Opting for immediate for now, could be queued.
  foreach ($sms as $number => $message) {
    $call = new VoipCall(array());
    $call->setDestNumber($number);
    $voip_server = voip_default_server();
    $response = $voip_server->send_text($message, $call);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add topic flag options to the user register form.
 * Default telephone number settings for this site.
 */
function comminfo_notify_form_user_register_form_alter(&$form, &$form_state) {
  $default_value = array();

  // @todo Retrieve this.
  $topics = array(
    '1' => 'Employment',
    '2' => 'Food',
    '3' => 'Health',
    '5' => 'Fun and Family',
    '4' => 'Other',
  );

  $form['comminfo_notify'] = array(
    '#type' => 'fieldset',
    '#description' => t('Select topics to receive SMS event reminders.'),
    '#weight' => 6,
  );
  $form['comminfo_notify']['comminfo_topics'] = array(
    '#type' => 'checkboxes',
    '#options' => $topics,
    '#default_value' => $default_value,
  );
  $form['#validate'][] = 'comminfo_notify_form_user_register_validate';
}

/**
 * Implements hook_user_insert().
 * 
 * Add user flags to topics for topic subscriptions, and notifies SMS number
 * of subscriptions.
 */
function comminfo_notify_user_insert(&$edit, $account, $category) {
  if (isset($edit['comminfo_topics'])) {
    $tids = array_keys(array_filter($edit['comminfo_topics']));
    if (!empty($tids)) {
      foreach ($tids as $tid) {
        flag('flag', 'sms_topic_updates', $tid, $account);
      }
    }
  }

  // Notify user at actually stored number.
  $voipnumber = VoipNumber::load($account->field_sms_number['und'][0]['vnid']);
  $smsnumber = $voipnumber->getNumber();
  $txt = 'You have subscribed to incourage updates: ';
  $txt .= '';
  $txt .= 'To unsubscribe text \'STOP\' to xxx-xxx-xxxx';
  $call = new VoipCall(array());
  $call->setDestNumber($smsnumber);
  $voip_server = voip_default_server();
  $response = $voip_server->send_text($txt, $call);
}

/**
 * Implements hook_element_info_alter().
 *
 * Add our own defaults to the voipnumberfield widget.
 */
function comminfo_notify_element_info_alter(&$type) {
  $type['voipphonenumber_widget']['#process'][] = 'comminfo_notify_voipnumber_widget_process';
}

/**
 * Implements hook_voipscript_get_script_names().
 */
function comminfo_notify_voipscript_get_script_names() {
  return array(
    'comminfo_notify_incoming_sms',
  );
}

/**
 * Implements hook_voipscript_load_script().
 */
function comminfo_notify_voipscript_load_script($script_name, $params = NULL) {
  if ($script_name == 'comminfo_notify_incoming_sms') {
    $script = new VoipScript('comminfo_notify_incoming_sms');
    $script->addSet('request_result', '^comminfo_notify_voipscript_incoming_sms_parse(%inbound_text_contents, %caller_number)');
    $script->addSendText('%request_result');
    $script->addHangup('reset');
    return $script;
  }
}

/**
 * VoipScript callback.
 *
 * Handle incoming SMS.
 * @todo be developed: more options, check unsubscription.
 */
function comminfo_notify_voipscript_incoming_sms_parse($msg, $from) {
  $msg = trim($msg);
  if (empty($msg)) {
    return t('Empty message received.');
  }

  $entity_array = voipnumberfield_get_entity_by_number('user', 'field_sms_number', $from);
  if (empty($entity_array['user'])) {
    return t('Phone number not recognised. Registration by SMS yet to be implemented.');
  }

  $user = entity_load('user', array(key($entity_array['user'])));
  if ($msg == 'STOP') {
    // @todo Yes really! Check it is just a user subscribed to SMS and not
    // something important. We're being trusting (aka insecure) already!
    user_delete($user->uid);
    return t('You have been unsubscribed from updates.');
  }

  return t("To stop receiving messages send the message 'STOP'");
}

/**
 * Voiphonenumber_widget hook_element_info_alter #process callback.
 *
 * Custom default phone number element.
 */
function comminfo_notify_voipnumber_widget_process($element, $form_state, $complete_form) {
  $element['default'] = array(
    '#type' => 'hidden',
    '#value' => 1,
  );
  $element['type'] = array(
    '#type' => 'hidden',
    '#value' => 3,
  );
  $element['country'] = array(
    '#type' => 'hidden',
    '#value' => 'United States',
  );
  return $element;
}

/**
 * Voiphonenumber_widget hook_element_info_alter #element_validate callback.
 *
 * Add US code if required.
 */
function comminfo_notify_form_user_register_validate($form, &$form_state) {
  // Really basic start this one. But it should work for most cases along with
  // the validation done by voipnumber itself.
  if (substr(trim($form_state['values']['field_sms_number']['und'][0]['vnid']), 0, 2) != '+1') {
    $form_state['values']['field_sms_number']['und'][0]['vnid'] = '+1' . $form_state['values']['field_sms_number']['und'][0]['vnid'];
  }
  dsm($form_state);
}
